# Generated by Django 3.1.14 on 2025-05-24 04:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mysite.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20210705_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=mysite.middleware.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=110, unique=True, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
