# Generated by Django 6.0.2 on 2026-02-10 23:30

import django.db.models.deletion
import inventory_receiving.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('initial_quantity', models.PositiveIntegerField(help_text='Starting quantity (immutable after creation).')),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('is_unique', models.BooleanField(default=False)),
                ('length_in', models.PositiveIntegerField(default=0)),
                ('width_in', models.PositiveIntegerField(default=0)),
                ('height_in', models.PositiveIntegerField(default=0)),
                ('weight_oz', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('not_listed', 'Not Listed'), ('ebay', 'eBay'), ('etsy', 'Etsy'), ('website', 'Website'), ('sold_out', 'Sold Out')], default='not_listed', max_length=20)),
                ('date_listed', models.DateField(blank=True, null=True)),
                ('date_sold_out', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(help_text='Uppercase alphanumeric code used as SKU prefix (immutable).', max_length=10, unique=True)),
                ('next_sku_number', models.PositiveIntegerField(default=1001, help_text='Next SKU number to assign for this product type.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=inventory_receiving.models.ProductImage.get_upload_to)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory_receiving.product')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory_receiving.producttype'),
        ),
    ]
