# Generated by Django 6.0.2 on 2026-02-11 17:49

import inventory_receiving.models
import inventory_receiving.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_receiving', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=inventory_receiving.storages.inventory_receiving_storage, upload_to=inventory_receiving.models.ProductImage.get_upload_to),
        ),
    ]
