# Generated by Django 3.1.12 on 2021-08-07 11:50

from django.db import migrations, models
import tasks.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_by',
            field=models.DateTimeField(default=tasks.utils.next_day),
        ),
    ]
