# Generated by Django 3.1.12 on 2021-08-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210807_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='author',
        ),
    ]
