# Generated by Django 3.1.12 on 2021-08-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210807_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.TextField(blank=True),
        ),
    ]
